# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fa5f4ae464e1508b9b3f6cc3f38d6d24128894809c8a87b6db1a374cd23d098c8bcc8598a6d98b2b26c832744a428daa08deec1345563e5dc7e7eeb44f12176e

test:
  secret_key_base: 8e1dee6f6b5e0df85693bfa9ad5dae1f3ad64074942d55d35f98e5872999d48266d64ab0f0d5f9825576ca85db9d478fd1070691c6484ce7aed07a61ec341251

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
